#ifndef OUTPUT_H
#define OUTPUT_H

#define DEFAULT     "\e[39m"
#define BLACK       "\e[30m"
#define RED         "\e[31m"
#define LRED        "\e[91m"
#define GREEN       "\e[32m"
#define LGREEN      "\e[92m"
#define YELLOW      "\e[33m"
#define LYELLOW     "\e[93m"
#define BLUE        "\e[34m"
#define LBLUE       "\e[94m"
#define MAGENTA     "\e[35m"
#define LMAGENTA    "\e[95m"
#define CYAN        "\e[36m"
#define LCYAN       "\e[96m"
#define LGRAY       "\e[37m"
#define DGRAY       "\e[90m"
#define WHITE       "\e[97m"
#define GRAY        "\e[38;5;245m"
#define ORANGE      "\e[38;5;180m"

#define BDEFAULT     "\e[49m"
#define BBLACK       "\e[40m"
#define BRED         "\e[41m"
#define BLRED        "\e[101m"
#define BGREEN       "\e[42m"
#define BLGREEN      "\e[102m"
#define BYELLOW      "\e[43m"
#define BLYELLOW     "\e[103m"
#define BBLUE        "\e[44m"
#define BLBLUE       "\e[104m"
#define BMAGENTA     "\e[45m"
#define BLMAGENTA    "\e[105m"
#define BCYAN        "\e[46m"
#define BLCYAN       "\e[106m"
#define BLGRAY       "\e[47m"
#define BDGRAY       "\e[100m"
#define BWHITE       "\e[107m"

#define CRED         "\e[38;5;124m"
#define CLRED        "\e[38;5;198m"
#define CGREEN       "\e[38;5;34m"
#define CLGREEN      "\e[38;5;118m"
#define CYELLOW      "\e[38;5;3m"
#define CLYELLOW     "\e[38;5;226m"
#define CBLUE       "\e[38;5;26m"
#define CLBLUE      "\e[38;5;33m"
#define CMAGENTA     "\e[38;5;128m"
#define CLMAGENTA    "\e[38;5;164m"
#define CCYAN        "\e[38;5;6m"
#define CLCYAN       "\e[38;5;14m"
#define CORANGE      "\e[38;5;180m"

#endif /* OUTPUT_H */